### ISSUE TITLE
p.16 Big-O표기법 질문 있습니다!

### ISSUE THREAD

**Issue by ghost** [daeseokyoun/learn-algorithm-by-writing#8]
안녕하세요! 알고리즘 입문하려고 전자책으로 구매하여 잘 보고 있습니다.
알고리즘 문제를 풀 때 바로 코딩을 시작하는 것이 아닌, 정해진 템플릿으로 가능한 경우의 수를 먼저 고려한다는 점이 정말 좋은 것 같네요.

요청드릴 질문은, p.16에서 i는 n/2만큼 수행된다고 하셨는데, 
n = 16일 때, i = 8 ~ 16까지 총 9번 수행되니까 (n+1)/2 만큼 수행되는 것이 아닌가요?
물론 후술하신 것 처럼 곱의 계수는 Big-O표기에 의해 연산 크기에 큰 영향을 주지 않기 때문에 제외하겠지만요.

추가적으로 j가 logN만큼 수행되는 이유에 대해 조금만 자세히 설명해주시면 정말 감사하겠습니다.

감사합니다.^^

**Comment by daeseokyoun** [comment]
@Frog000 오, 잘봐주셔서 너무 감사합니다. 질문 주신 사항에 대해 답변을 드리겠습니다.

- `n = 16`일 때, i = 8...16까지는 정확히 `n/2`가 맞습니다. 숫자는 말씀하신대로 9개가 맞는데요, for loop를 수행하는 입장에서는 `8 step`이 됩니다. 즉, `n/2`번의 루프가 수행되는 겁니다.
- j 의 루프가 logN인 이유는,
  - `n = 16`일때, j = 2, 4, 8, 16 => 4번 수행됩니다.
  - `n = 32`일때, j = 2, 4, 8, 16, 32 => 5번 수행됩니다.
  - `n = 64`일때, j = 2, 4, 8, 16, 32, 64 => 6번 수행됩니다.
    ![image](https://user-images.githubusercontent.com/9688075/134344809-24e0da5a-edec-4a88-b205-e642aeb82fcc.png)
- 아마 logN의 밑수가 10으로 생각하신것 같은데요, 다른 규칙과 비슷하게 log의 밑수가 어떤 상수든 실제 big-O 표기법에는 크게 영향이 없다고 합니다. 질문 주신 logN이 밑수 log2N으로 생각하시면, 주어진 N에 대해 j의 루프는 log2N만큼 수행될 것입니다.

다른 질문이 있으시면 언제든 편하게 주세요.
빠르게 답변 드릴 수 있도록 할께요.

감사합니다. :-)

**Comment by ghost** [comment]
아~ 그렇군요, 자세한 설명 감사합니다!!
